Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 20

AllCops:
  Exclude:
    - 'lib/curs/asciidoctor/extensions/table_column_cell_role/**'
