'use strict'
const fs = require('fs')
const path = require('path')
const OpalBuilder = require('opal-compiler').Builder
const rootPath = path.join(__dirname, '..')

const compile = () => {
  const opalBuilder = OpalBuilder.create()
  opalBuilder.appendPaths('node_modules/opal-compiler/src/stdlib')
  opalBuilder.appendPaths('ruby/lib/curs/asciidoctor/extensions')
  opalBuilder.setCompilerOptions({ dynamic_require_severity: 'ignore' })
  const code = opalBuilder.build('js/table_column_cell_role').toString()
    // remove inline comments: /* Generated Generated by Opal 1.2.3 */
    .replace(/\/\* Generated by Opal (.*) \*\/\n/gm, '')
  fs.writeFileSync(path.join(rootPath, 'lib', 'table-column-cell-role.js'), code, 'utf8')
}

compile()
